title: Ben Smithgall's site
description: Interactive News Developer at the New York Times. Previously with Spotify, U.S. Digital Service, and Code for America.
url: https://bensmithgall.com
markdown: kramdown
permalink: /:categories/:title
baseurl: /
rdiscount extensions: [smart]
paginate: 5
future: false
highlighter: rouge
plugins: [jekyll-paginate]
