name: Ben Smithgall's site
description: I work at the US Digital Service. Previously at Code for America, Spotify, and Obama 2012.
url: http://bensmithgall.com
markdown: kramdown
permalink: /blog/:title
baseurl: /
rdiscount extensions: [smart]
paginate: 5
paginate_path: "/blog/page:num"
future: false
highlighter: rouge
gems: [jekyll-paginate]
